# Http-Kontext Development (+ upstream frontend)
map $http_x_forwarded_proto $forwarded_proto {
    default $http_x_forwarded_proto;
    ""      $scheme;
}

log_format main_json escape=json
  '{ "time":"$time_iso8601", "remote_addr":"$remote_addr", '
  '"request":"$request", "status":$status, '
  '"bytes_sent":$body_bytes_sent, "referer":"$http_referer", '
  '"user_agent":"$http_user_agent", "request_time":$request_time }';

access_log /var/log/nginx/access.log main_json;

sendfile on;
tcp_nopush on;
keepalive_timeout 65;
client_max_body_size 25M;

limit_req_zone $binary_remote_addr zone=api_limit:10m   rate=10r/s;
limit_req_zone $binary_remote_addr zone=portal_limit:10m rate=5r/s;
limit_req_zone $binary_remote_addr zone=login_limit:10m  rate=2r/s;

upstream api_backend {
    server api:8000;
    keepalive 32;
}

upstream portal_backend {
    server api:8000;
    keepalive 16;
}

upstream frontend {
    server frontend:80;
    keepalive 16;
}
